version: "3"
services:
  nonebot:
    build: .
    ports:
      - "8080:8080" # 映射端口到宿主机 宿主机端口:容器端口
      - "5700:5700"
    env_file:
      - ".env.dev" # fastapi 使用的环境变量文件
    environment:
      - ENVIRONMENT=dev
      - APP_MODULE=bot:app
      - MAX_WORKERS=1
    network_mode: bridge
